name: Daily Routine Workflow

on:
  schedule:
    - cron: "0 20 * * *" # Runs at 20:00 UTC (Paris is UTC+2)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2 # Checkout the repository content to github runner.

      - name: Setup Python Version
        uses: actions/setup-python@v2
        with:
          python-version: 3.6 # Install the python version needed

      - name: Install Python dependencies
        # previous pafy patch install : python -m pip install -e git+git://github.com/mohamed-challal/pafy.git@develop#egg=pafy
        run: |
          python -m pip install --upgrade pip requests
          python -m pip install psycopg2
          python -m pip install youtube_dl
          python -m pip install -e https://github.com/Sources-Hugo-Decrypte/pafy.git@develop#egg=pafy
          python -m pip install scrapetube
          python -m pip install urllib3

      - name: Set private ytb api key
        run: |
          rm ~/.config/mps-youtube/cache_py*
          mpsyt set api_key ${{ secrets.HDS_YOUTUBE_API_KEY }}

      - name: Daily routine
        env :
            HDS_YOUTUBE_API_KEY: ${{ secrets.HDS_YOUTUBE_API_KEY }}
            HDS_DBSERVER_CONN_STRING: ${{ secrets.HDS_DBSERVER_CONN_STRING }}
            HDS_GMAIL_ADDRESS: ${{ secrets.HDS_GMAIL_ADDRESS }}
            HDS_GMAIL_APP_PASSWORD: ${{ secrets.HDS_GMAIL_APP_PASSWORD }}
        run: python src/main.py

      - name : Send email if workflow failed
        if: ${{ failure() }}
        uses: dawidd6/action-send-mail@v2
        with:
          # mail server settings
          server_address: smtp.gmail.com
          server_port: 465
          # user credentials
          username: ${{ secrets.HDS_GMAIL_ADDRESS }}
          password: ${{ secrets.HDS_GMAIL_APP_PASSWORD }}
          # email subject
          subject: ${{ github.workflow }} | ${{ job.status }}
          # email body as text
          body: Find worflow log at ${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}
          # comma-separated string, send email to
          to: ${{ secrets.HDS_GMAIL_ADDRESS }}
          # from email name
          from: Github workflow
